### ISSUE TITLE
postscript file tries to be a urdf file?

### ISSUE THREAD

**Issue by josch** [ros/kdl_parser#16]
Hi,

the repository contains `kdl_parser_py/test/kdl_parser_py.urdf` which is not a urdf file but a postscript document containing just a single image:

![prefix-000](https://user-images.githubusercontent.com/84850/42727864-39c91464-87ae-11e8-82e7-b090daa3e280.png)

How does this make sense?

**Comment by sloretz** [comment]
Wow, that's pretty strange. It has been there a while too: fedfd656fdd2f1687b463d8fb27eaad6a8e5bf18 ros/robot_model#114. 

@josch would you be willing to make PRs to `indigo-devel`, `kinetic-devel`, `melodic-devel` with this file deleted? 

The bottom middle terminal in the screenshot offers an explanation. It looks like @jacquelinekay ran `import kdl_parser_py.urdf` in bash instead of python.

`man import` says
```
       import  -  saves any visible window on an X server and outputs it as an
       image file. You can capture a single window, the entire screen, or  any
       rectangular portion of the screen.
```

That created an image file with a name that made it look like a plausible URDF file. Probably convincing enough to not be noticed when adding a bunch of files to the commit (or maybe `git add --all`). Github doesn't render the image in the diff view because it's too large, so it was probably overlooked in the PR which had a bunch of other files.

**Comment by josch** [comment]
I fear that I will not be able to get to doing these PRs any time soon, sorry. :(
